# Generated by Django 5.2.1 on 2025-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_exchangeproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
