# Generated by Django 5.2.1 on 2025-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_exchangeproposal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
